[tool.poetry]
name = "kube-notify"
version = "0.1.1"
description = "A simple python app to relay k8s events to gotify"
authors = ["wikle <loic97429@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
kube-notify = "kube_notify.app:main"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
argparse = "^1.4.0"
PyYAML = "^6.0.1"
kubernetes-asyncio = "^30.1.0"
DateTime = "^5.5"
pytz = "^2024.1"
importlib-metadata = "^7.1.0"

[tool.poetry.dev-dependencies]
pre-commit = "^3.7.1"
black = "^24.4.2"
pytest = "^8.2.1"
pytest-asyncio = "^0.23.7"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
